# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 225d2cce924e15d7c30dec5f7aa45947bda2fa6c411a77b260315c98ec23069a50b7aad09c641105672f4a1415726428211d2c673804bc9888dc3406270a737b

test:
  secret_key_base: ba0f179f5b0596a54b0c459c29f0ed404ba8f84e6a7e3d7d5d646a5f7bd0ad33686cda89428a6f933788e21ae398c7d6c3a28e6cab1413b348f2fc497f4eab7f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
